# Numpy

In [1]:
import numpy as np
a = np.array([10,20,30,40])
print(type(a))


<class 'numpy.ndarray'>


In [2]:
b = np.array((10,20,30,40))
print(b)

[10 20 30 40]


In [3]:
c = np.array([[10,20,30,40],[10,20,30,40]])
print(c)

[[10 20 30 40]
 [10 20 30 40]]


In [6]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[:3])
print(arr.dtype)

[1 2 3]
int32


In [7]:
arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [8]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [9]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [10]:
a = np.ones(10)
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [11]:
n = np.identity(3)
print(n)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
p = np.zeros([4,5])
print(p)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [16]:
a = np.arange(100)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [17]:
a = np.linspace(-2,2,10)
print(a)

[-2.         -1.55555556 -1.11111111 -0.66666667 -0.22222222  0.22222222
  0.66666667  1.11111111  1.55555556  2.        ]


In [18]:
print(np.random.randint(10))

3


In [19]:
for i in range(100):
    print(np.random.randint(10))

7
8
6
3
7
7
7
5
2
6
4
9
3
7
0
2
5
7
6
1
1
5
7
2
0
4
5
5
1
7
7
6
8
9
3
3
1
2
3
9
6
3
2
9
7
2
7
3
0
9
3
4
9
1
5
2
4
2
7
0
5
4
8
4
8
5
0
0
9
3
7
3
4
8
4
6
1
2
6
0
3
2
6
8
8
9
3
6
5
9
6
2
7
0
6
7
8
2
7
1


In [27]:
q = np.random.choice(5,100)
print(q)

[0 0 3 2 4 2 0 0 4 2 4 4 3 2 2 2 1 2 4 4 1 1 3 2 4 4 0 0 4 2 4 2 3 3 0 3 4
 0 4 4 0 1 1 2 4 3 4 3 0 4 1 2 4 0 0 3 1 2 4 4 3 3 3 0 4 1 3 1 3 0 4 3 1 0
 3 2 1 0 0 1 1 2 1 2 1 3 0 3 3 4 0 2 4 4 0 0 0 3 2 3]


In [26]:
print(q)

0


In [23]:
a = np.random.choice(['A','G','C','D','E'])
print(a)

A


In [30]:
f = open("h2.txt","a")
f.write("I Love Python\n")
f.close()