# Practice

In [1]:
import numpy as np
a = np.array([10,20,30,40,50])
print(a)

[10 20 30 40 50]


In [2]:
b = np.array((1,20,30,40,50))
print(b)

[ 1 20 30 40 50]


In [4]:
c = np.array([[10,20,30],[40,50,60]])
print(c)

[[10 20 30]
 [40 50 60]]


In [5]:
d = np.array([10,20,30,40,50])
print(d[1]+d[2])

50


In [7]:
print(d[0])
print(d[1])
print(d[2])
print(d[3])
print(d[4])

10
20
30
40
50


In [8]:
x = np.array([[10,20,30,40,50],[60,70,80,90,100]])
print('2nd element of the first row is:',x[0,1])

2nd element of the first row is: 20


In [9]:
print('4th element of the second row is: ', x[1,3])

4th element of the second row is:  90


# 3-D Array:

In [29]:
arr = np.array([[[2,3,5],[5,6,7]],[[8,9,10],[11,12,13]]])
print(arr[1,1,2])

13


In [32]:
print(x[0,-2])

40
